bookmark/urls.py
from django.conf.urls import url
from bookmark.views import *
from account.views import *
from . import views
urlpatterns = [
    url(r'^$', views.buy_subscribe, name='index'),
    #url(r'^$', AccountLV.as_view(), name='index'),

    url(r'^(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),
    #url(r'^(?P<pk>\d+)/$', AccountDV.as_view(), name='detail'),

    # Example: /add/
    url(r'^add/$',
        views.add, name="add",
    ),

    # Example: /add/
    url(r'^buy/$',
        BookmarkCreateView.as_view(), name="add",
    ),


    # Example: /change/
    url(r'^change/$',
        views.subscribing_list, name="change",
    ),

    # Example: /99/update/
    url(r'^(?P<pk>[0-9]+)/update/$',
        BookmarkUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$',
        BookmarkDeleteView.as_view(), name="delete",
    ),
]

buy/urls.py
from django.conf.urls import url

from photo.views import *

urlpatterns = [

    # Example: /
    url(r'^$', AlbumLV.as_view(), name='index'),
    # Example: /album/, same as /
    url(r'^album/$', AlbumLV.as_view(), name='menu_list'),

    # Example: /album/99/
    url(r'^menu/(?P<pk>\d+)/$', AlbumDV.as_view(), name='menu_detail'),

    # Example: /photo/99/
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),

    # Example: /album/add/
    url(r'^album/add/$',
        AlbumPhotoCV.as_view(), name="album_add",
    ),

    # Example: /album/change/
    url(r'^album/change/$',
        AlbumChangeLV.as_view(), name="album_change",
    ),

    # Example: /album/99/update/
    url(r'^album/(?P<pk>[0-9]+)/update/$',
        AlbumPhotoUV.as_view(), name="album_update",
    ),

    # Example: /album/99/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$',
        AlbumDeleteView.as_view(), name="album_delete",
    ),

    # Example: /photo/add/
    url(r'^photo/add/$',
        PhotoCreateView.as_view(), name="photo_add",
    ),

    # Example: /photo/change/
    url(r'^photo/change/$',
        PhotoChangeLV.as_view(), name="photo_change",
    ),

    # Example: /photo/99/update/
    url(r'^photo/(?P<pk>[0-9]+)/update/$',
        PhotoUpdateView.as_view(), name="photo_update",
    ),

    # Example: /photo/99/delete/
    url(r'^photo/(?P<pk>[0-9]+)/delete/$',
        PhotoDeleteView.as_view(), name="photo_delete",
    ),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),
    url(r'^gudok/', include('gudok.urls', namespace='gudok')),
    url(r'^account/', include('account.urls',namespace='account')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bookmark/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.contrib.auth.models import User
from photo.models import *
# Create your models here.

@python_2_unicode_compatible
class Bookmark(models.Model):
    title = models.ForeignKey(Album, blank=True,null=True)
    amount = models.IntegerField(default=0)
    photo = models.ForeignKey(Photo, blank=True,null=True)
    price = models.IntegerField(default=0)
    state = models.CharField(max_length=100, blank=True, null=True)
    star = models.CharField(max_length=100, blank=True, null=True)
    owner = models.ForeignKey(User, null=True)
    maker = models.CharField(max_length=100, blank=True, null=True, default='미정')

    class Meta:
        ordering = ['title']

    def __str__(self):
        return str(self.title)

# 그룹을 만들건데 이 그룹이 사용자로 되는거지
class SubGroup(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    price = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return str(self.title)


# 구독한 목록 객채
class SubList(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    price = models.CharField(max_length=100, blank=True, null=True)
    owner = models.ForeignKey(SubGroup, null=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return str(self.title)

bookmark/templates/bookmark/bookmark_change_list.html
{% extends "base.html" %}

{% block title %}bookmark_change_list.html{% endblock %}

{% block content %}
<div id="content" style="margin-left:40px;">
</br></br></br>
    <h1>평점주기 - {{user}}</h1>
</br>
    <table class="change-list">
        <tr>
            <th>제품명&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</th>
            <th>수량&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</th>
            <th>평가 하기</th>
        </tr>

        {% for item in bookmark %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.amount }}개</td>
            <td><a href="{% url 'bookmark:update' item.id %}">별점 주기</a></td>
        </tr>
        {% endfor %}
    </table>

</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends "base.html" %}

{% block title %}bookmark_confirm_delete.html{% endblock %}

{% block content %}
<div id="content">

    <h1>Bookmark Delete</h1>

    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" />
    </form>

</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %}Django Bookmark Detail{% endblock %}

{% block content %}
<div id="content">
    <h1>{{ object.title }}</h1>

    <ul>
        <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_form.html
{% extends "base.html" %}

{% block title %}bookmark_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
 <div class="container">
<b/>
      <!-- Page Heading/Breadcrumbs -->
     <br />
     <br />



      <h1 class="mt-3 mb-8"><h1>구매자_구독 등록</h1>
      </h1>
<br />
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          각 품목에 대한 수량과 원하는 가격을 정해주세요.
            <br />
            <br />
 <form action="." method="post">{% csrf_token %}

    {% if form.errors %}
    <p class="errornote">정확한 값을 입력해주세요.</p>
    {% endif %}


<b/>
    <fieldset class="aligned">

        <div class="form-row">
            <h3> 품목 :　</h3>    {{ form.title }}
        </div>

        <div class="form-row">
            <h3> 가격 :　</h3>    {{ form.price}}
        </div>

        <div class="form-row">
            <h3> 수량 :　</h3> {{ form.amount }}
        </div>

    </fieldset>

    <fieldset class="aligned">
            {{ form.star.label_tag }} {{ form.star }}
    </fieldset>

    <div class="submit-row">
        <input type="submit" value="Submit"/>
    </div>

    <script type="text/javascript">document.getElementById('id_title').focus();</script>
    </form>

</div>
      </ol>



{% endblock %}
    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Econovation</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{% block title %}Django Bookmark List{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content" style="margin-left:40px;">
    <br/><br/><br/>
    <h2>{% firstof user.get_short_name user.get_username %}님의 구독 장바구니</h2>

    <ul>
        <div class="col">
        <div class="row">
          {% for SubList in bookmark %}
        <div class="mb-0" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="card">
          <div class="card-header" role="tab" id="headingOne">
              <a data-toggle="collapse" data-parent="#accordion" aria-expanded="true" aria-controls="collapseOne">
                 <li>물건 : {{ SubList.title }}</li>
            	<li>가격 : {{ SubList.price }} 원</li>
                 <li>개수 : {{ SubList.amount }} 개</li>

              </a>

          </div>



        {% endfor %}
            </div>
            </div>
    </ul>


    <a href="http://localhost:8000/bookmark/add/" >
      <button type="button">구독 신청</button>
    </a>
  </div>
</div>
{% endblock %}

bookmark/templates/bookmark/sublist_list.html
{% extends "base.html" %}

{% block title %}Django SubList List{% endblock %}

{% block content %}
<div id="content">
    <h1>{% firstof user.get_short_name user.get_username %}님이 구독한 목록</h1>

    <ul>
        {% for SubList in object_list %}
            <li>{{ SubList.title }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}