buy/urls.py
from django.conf.urls import url

from photo.views import *

urlpatterns = [

    # Example: /
    url(r'^$', AlbumLV.as_view(), name='index'),
    # Example: /album/, same as /
    url(r'^album/$', AlbumLV.as_view(), name='menu_list'),

    # Example: /album/99/
    url(r'^menu/(?P<pk>\d+)/$', AlbumDV.as_view(), name='menu_detail'),

    # Example: /photo/99/
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),

    # Example: /album/add/
    url(r'^album/add/$',
        AlbumPhotoCV.as_view(), name="album_add",
    ),

    # Example: /album/change/
    url(r'^album/change/$',
        AlbumChangeLV.as_view(), name="album_change",
    ),

    # Example: /album/99/update/
    url(r'^album/(?P<pk>[0-9]+)/update/$',
        AlbumPhotoUV.as_view(), name="album_update",
    ),

    # Example: /album/99/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$',
        AlbumDeleteView.as_view(), name="album_delete",
    ),

    # Example: /photo/add/
    url(r'^photo/add/$',
        PhotoCreateView.as_view(), name="photo_add",
    ),

    # Example: /photo/change/
    url(r'^photo/change/$',
        PhotoChangeLV.as_view(), name="photo_change",
    ),

    # Example: /photo/99/update/
    url(r'^photo/(?P<pk>[0-9]+)/update/$',
        PhotoUpdateView.as_view(), name="photo_update",
    ),

    # Example: /photo/99/delete/
    url(r'^photo/(?P<pk>[0-9]+)/delete/$',
        PhotoDeleteView.as_view(), name="photo_delete",
    ),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),
    url(r'^gudok/', include('gudok.urls', namespace='gudok')),
    url(r'^account/', include('account.urls',namespace='account')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.conf.urls import url

from photo.views import *
from . import views
urlpatterns = [

    # Example: /

    url(r'^album0/$', AlbumLV.as_view(), name='index',),
    url(r'^album1/$', AlbumLV2.as_view(), name='index2',),
    url(r'^album2/$', AlbumLV3.as_view(), name='index3',),
    url(r'^album3/$', AlbumLV4.as_view(), name='index4',),
    # Example: /album/, same as /
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),
    url(r'^buy/$', views.buy, name='buy'),
    # Example: /album/99/
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),

    # Example: /photo/99/
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),

    # Example: /album/add/
    url(r'^album/add/$',
        AlbumPhotoCV.as_view(), name="album_add",
    ),

    # Example: /album/change/
    url(r'^album/change/$',
        AlbumChangeLV.as_view(), name="album_change",
    ),

    # Example: /album/99/update/
    url(r'^album/(?P<pk>[0-9]+)/update/$',
        AlbumPhotoUV.as_view(), name="album_update",
    ),

    # Example: /album/99/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$',
        AlbumDeleteView.as_view(), name="album_delete",
    ),

    # Example: /photo/add/
    url(r'^photo/add/$',
        PhotoCreateView.as_view(), name="photo_add",
    ),

    # Example: /photo/change/
    url(r'^photo/change/$',
        PhotoChangeLV.as_view(), name="photo_change",
    ),

    # Example: /photo/99/update/
    url(r'^photo/(?P<pk>[0-9]+)/update/$',
        PhotoUpdateView.as_view(), name="photo_update",
    ),

    # Example: /photo/99/delete/
    url(r'^photo/(?P<pk>[0-9]+)/delete/$',
        PhotoDeleteView.as_view(), name="photo_delete",
    ),
]

templates/photo/urls.py
from django.conf.urls import url

from photo.views import *

urlpatterns = [

    # Example: /

    url(r'^album0/$', AlbumLV.as_view(), name='index',),
    url(r'^album1/$', AlbumLV2.as_view(), name='index2',),
    url(r'^album2/$', AlbumLV3.as_view(), name='index3',),
    url(r'^album3/$', AlbumLV4.as_view(), name='index4',),
    # Example: /album/, same as /
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),

    # Example: /album/99/
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),

    # Example: /photo/99/
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),

    # Example: /album/add/
    url(r'^album/add/$',
        AlbumPhotoCV.as_view(), name="album_add",
    ),

    # Example: /album/change/
    url(r'^album/change/$',
        AlbumChangeLV.as_view(), name="album_change",
    ),

    # Example: /album/99/update/
    url(r'^album/(?P<pk>[0-9]+)/update/$',
        AlbumPhotoUV.as_view(), name="album_update",
    ),

    # Example: /album/99/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$',
        AlbumDeleteView.as_view(), name="album_delete",
    ),

    # Example: /photo/add/
    url(r'^photo/add/$',
        PhotoCreateView.as_view(), name="photo_add",
    ),

    # Example: /photo/change/
    url(r'^photo/change/$',
        PhotoChangeLV.as_view(), name="photo_change",
    ),

    # Example: /photo/99/update/
    url(r'^photo/(?P<pk>[0-9]+)/update/$',
        PhotoUpdateView.as_view(), name="photo_update",
    ),

    # Example: /photo/99/delete/
    url(r'^photo/(?P<pk>[0-9]+)/delete/$',
        PhotoDeleteView.as_view(), name="photo_delete",
    ),
]

photo/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.core.urlresolvers import reverse

from photo.fields import ThumbnailImageField

from django.contrib.auth.models import User

# Create your models here.

@python_2_unicode_compatible
class Album(models.Model):
    name = models.CharField(max_length=50)
    category = models.IntegerField(default=4)
    description = models.CharField('One Line Description', max_length=100, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))

@python_2_unicode_compatible
class Photo(models.Model):
    album = models.ForeignKey(Album)
    #한 줄 설명
    origin = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('상세설명', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)
    cnt = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    Subscription_ratings=models.IntegerField(default=0)
    purchase_after_sub=models.IntegerField(default=0)
    owner = models.ForeignKey(User, null=True)




    class Meta:
        ordering = ['origin']

    def __str__(self):
        return self.origin

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

templates/photo/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.core.urlresolvers import reverse

from photo.fields import ThumbnailImageField

from django.contrib.auth.models import User

# Create your models here.

@python_2_unicode_compatible
class Album(models.Model):
    name = models.CharField(max_length=50)
    category = models.IntegerField(default=4)
    description = models.CharField('One Line Description', max_length=100, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))

@python_2_unicode_compatible
class Photo(models.Model):
    album = models.ForeignKey(Album)
    #한 줄 설명
    origin = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('상세설명', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)
    cnt = models.CharField(max_length=50)
    price = models.CharField(max_length=50)
    Subscription_ratings=models.CharField(max_length=50)
    purchase_after_sub=models.CharField(max_length=50)
    owner = models.ForeignKey(User, null=True)




    class Meta:
        ordering = ['origin']

    def __str__(self):
        return self.origin

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

photo/forms.py
from photo.models import Album, Photo
from django.forms.models import inlineformset_factory

PhotoInlineFormSet = inlineformset_factory(Album, Photo,
    fields = ['image', 'origin', 'description','cnt','price' ,'Subscription_ratings','purchase_after_sub'],
    extra = 2)

templates/photo/forms.py
from photo.models import Album, Photo
from django.forms.models import inlineformset_factory

PhotoInlineFormSet = inlineformset_factory(Album, Photo,
    fields = ['image', 'origin', 'description','cnt','price' ,'Subscription_ratings','purchase_after_sub'],
    extra = 2)

templates/photo/views.py
from django.views.generic import ListView, DetailView
from photo.models import Album, Photo

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from mysite.views import LoginRequiredMixin

# Create your views here.

class AlbumLV(ListView):
    model = Album
    def get_queryset(self):
        return Album.objects.filter(category=1)

class AlbumLV2(ListView):
    model = Album
    def get_queryset(self):
        return Album.objects.filter(category=2)

class AlbumLV3(ListView):
    model = Album
    def get_queryset(self):
        return Album.objects.filter(category=3)

class AlbumLV4(ListView):
    model = Album
    def get_queryset(self):
        return Album.objects.filter(category=4)

class AlbumDV(DetailView):
    model = Album

class PhotoDV(DetailView):
    model = Photo

#--- Add/Change/Update/Delete for Photo
class PhotoCreateView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['album', 'origin', 'image', 'description','cnt','price','Subscription_ratings','purchase_after_sub']
    success_url = reverse_lazy('photo:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PhotoCreateView, self).form_valid(form)

class PhotoChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)

class PhotoUpdateView(LoginRequiredMixin, UpdateView) :
    model = Photo
    fields = ['album', 'origin', 'image', 'description','cnt','price','Subscription_ratings','purchase_after_sub']
    success_url = reverse_lazy('photo:index')

class PhotoDeleteView(LoginRequiredMixin, DeleteView) :
    model = Photo
    success_url = reverse_lazy('photo:index')

#--- Add/Change/Update/Delete for Album
#--- Change/Delete for Album
class AlbumChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/album_change_list.html'

    def get_queryset(self):
        return Album.objects.filter(owner=self.request.user)

class AlbumDeleteView(LoginRequiredMixin, DeleteView) :
    model = Album
    success_url = reverse_lazy('photo:index')


#--- InlineFormSet View
#--- Add/Update for Album
from django.shortcuts import redirect
from photo.forms import PhotoInlineFormSet

class AlbumPhotoCV(LoginRequiredMixin, CreateView):
    model = Album
    fields = ['name', 'description']

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoCV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormSet()
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect('photo:album_detail', pk=self.object.id)
        else:
            return self.render_to_response(self.get_context_data(form=form))

class AlbumPhotoUV(LoginRequiredMixin, UpdateView):
    model = Album
    fields = ['name', 'description']

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoUV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = PhotoInlineFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.object.get_absolute_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

photo/templates/photo/album_change_list.html
{% extends "base.html" %}

{% block title %}album_change_list.html{% endblock %}

{% block content %}
<div id="content" style="margin-left:40px;">

    <h1>Album Change - {{user}}</h1>

    <table class="change-list">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>

        {% for item in object_list %}
        <tr>
            <td>{{ item.name }}</td>
            <td>{{ item.description|linebreaks }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'photo:album_update' item.id %}">Update</a></td>
            <td><a href="{% url 'photo:album_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>

</div>
{% endblock %}

photo/templates/photo/album_confirm_delete.html
{% extends "base.html" %}

{% block title %}album_confirm_delete.html{% endblock %}

{% block content %}
<div id="content" style="margin-left:40px;">

    <h1>Album Delete</h1>

    <form action="." method="post"> {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" />
    </form>

</div>
{% endblock %}

photo/templates/photo/album_detail.html
{% extends "base.html" %}

{% block title %}album_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<div id="content" style="margin-left:40px;">
<br/><br/><br/><br/>
    <h2 style="display:inline">{{ object.name }}</h2>
    &emsp;<b><i>{{ object.description }}</i></b>

    <hr/>
     <div class="row">
         {% for photo in object.photo_set.all %}
        <div class="col-mg-2 col-lg-2 portfolio-item">
          <div class="card h-100">
            <a href="{{ photo.get_absolute_url }}"><img class="card-img-top" src="{{ photo.image.thumb_url }}" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#"> <li>{{ photo.origin }}</li></a>
              </h4>
              <p> 평점 점수 : {{ photo.Subscription_ratings }}점 <br/> 재 구매 횟수 : {{ photo.purchase_after_sub }}번  </div>
          </div>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

photo/templates/photo/album_form.html
{% extends "base.html" %}

{% block title %}album_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div style="margin-left:40px;" id="content">
</br></br></br>
<div class="row">



    {% if form.is_multipart or formset.is_multipart %}
    <form enctype="multipart/form-data" method="post" action=".">
    {% else %}
    <form method="post" action=".">
    {% endif %}
    {% csrf_token %}

    {% if form.errors %}
    <p class="errornote">Wrong! Please correct the FORM error(s) below.</p>
    {% endif %}
    {% if formset.errors %}
    <p class="errornote">Wrong! Please correct the FORMSET error(s) below.</p>
    {% endif %}


    <h4>Create or Update Album contents.</h4>

    <fieldset class="aligned">
        <div class="form-row">
            {{ form.name.label_tag }} {{ form.name }}
        </div>
        <div class="form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>
    </fieldset>

    <h4>Create or Update Photo contents.</h4>

    {{ formset.management_form }}
    {% for form in formset %}
        {{ form.id }}
    <fieldset class="aligned">
        <div class="form-row">
            {{ form.image.label_tag }} {{ form.image }}
        </div>
        <div class="form-row">
            {{ form.title.label_tag }} {{ form.title }}
        </div>
        <div class="form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>
    </fieldset>
    {% endfor %}

    <div class="submit-row">
        <input type="submit" value="Submit"/>
    </div>

    <script type="text/javascript">document.getElementById('id_name').focus();</script>

    </form>

</div>
    </div>
{% endblock %}

photo/templates/photo/album_list.html
{% extends "base.html" %}

{% block title %}album_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<div id="content" style="margin-left:40px;">

<br/><br/><br/>
    {% for item in object_list %}

    <div class="clear_float">
        <h2 style="display:inline"><a href="{% url 'photo:album_detail' item.id %}">{{ item.name }}</a></h2>
        &emsp;<b><i>{{ item.description }}</i></b>
    </div>

    <hr align=""width=""size="10">

    <div class="album-list">
        <div class="row">
        {% for photo in item.photo_set.all|slice:":10" %}
        <div class="col-mg-2 col-sm-2  portfolio-item">
            <div class="card h-100">
            <a href="{{ photo.get_absolute_url }}"><img class="card-img-top" src="{{ photo.image.thumb_url }}"alt="" /></a>
           <div class="card-body">
              <h4 class="card-title"> </h4>
                <a href="{{ photo.get_absolute_url }}"> {{photo.origin}}</a>
             <p>평점 점수 : {{ photo.Subscription_ratings }}점 <br/> 재 구매 횟수 : {{ photo.purchase_after_sub }}번 </p> </div>
            </div>
          </div>




        {% endfor %}
    </div>
</div>

    {% endfor %}

</div>
{% endblock %}

photo/templates/photo/buy_ok.html
{% extends "base.html" %}

{% block title %}gudok_add.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content" style="margin-left:40px;">

    <h1>{{user}}님, 농산물 구매 가 성공하셨습니다.</h1>
    <h2>축하드립니다.</h1>
      {{account}}

</div>
{% endblock %}

photo/templates/photo/photo_change_list.html
{% extends "base.html" %}

{% block title %}photo_change_list.html{% endblock %}

{% block content %}
<div id="content" style="margin-left:40px;">

    <h1>Photo Change - {{user}}</h1>

    <table class="change-list">
        <tr>
            <th>Album</th>

            <th>origin</th>
            <th>Description</th>
            <th>cnt</th>
            <th>price</th>
            <th>subscription_ratings</th>
            <th>purchase_after_sub</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>

        {% for item in object_list %}
        <tr>
            <td>{{ item.album }}</td>
            <td>{{ item.origin }}</td>
            <td>{{ item.description|linebreaks }}</td>
            <td>{{item.cnt}}</td>
            <td>{{item.price}}</td>
            <td>{{item.Subscription_ratings}}</td>
            <td>{{item.purchase_after_sub}}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'photo:photo_update' item.id %}">Update</a></td>
            <td><a href="{% url 'photo:photo_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>

</div>
{% endblock %}

photo/templates/photo/photo_confirm_delete.html
{% extends "base.html" %}

{% block title %}photo_confirm_delete.html{% endblock %}

{% block content %}
<div id="content" style="margin-left:40px;">

    <h1>Photo Delete</h1>

    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" />
    </form>

</div>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends "base.html" %}

{% block title %}photo_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<div id="content" style="margin-left:40px;">

    <h2>{{ object.origin }}</h2>

    <table class="photo-detail">
    <tr>
    <td>
        <a href="{{ object.image.url }}">
        <img style="max-width:100%" src="{{ object.image.url }}" />
        </a>
    </td>

    <td>
    <ul>
        <li>원산지</li>
        <p><a href="{% url 'photo:album_detail' object.album.id %}">{{ object.album.name }}</a></p>
        <li>가격</li>
        <p>{{object}}원</p>
        <li>수량</li>
        <p>{{object.cnt}}개</p>
        <li>구독 점수 </li>
        <p>{{object.Subscription_ratings}}점</p>
        <li>구독 후 재구매 횟수</li>
        <p>{{ object.purchase_after_sub}}번</p>
        <li>Photo Description</li>
        {% if object.description %}<p>{{ object.description|linebreaks }}</p>
        {% else %}<p>(blank)</p>{% endif %}
        <form action="http://localhost:8000/photo/buy/" method="post">{% csrf_token %}
        <input type="submit" value="전송" />
        </form>

    </ul>
    </td>
    </tr></table>

</div>
{% endblock %}

photo/templates/photo/photo_form.html
{% extends "base.html" %}

{% block title %}photo_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content" style="margin-left:40px;">

</br></br></br>
    <h1>{{user}}님의 농수산물 등록하기</h1>


    <div class="row">
    {% if form.is_multipart %}
    <form enctype="multipart/form-data" method="post" action=".">

    {% else %}
    <form method="post" action=".">
    {% endif %}
    {% csrf_token %}

    {% if form.errors %}
    <p class="errornote">Wrong! Please correct the error(s) below.</p>
    {% endif %}


    <p>이곳은 농수산물을 등록하는 곳 입니다.</p>
    <fieldset class="aligned">

        <div class="form-row">

            {{ '품목 : ' }} {{ form.album }}
            <button type="button"><a href="{% url 'photo:album_add' %}">Add Album</a></button>
        </div>

        <div class="form-row">
            {{ '사진 : ' }} {{ form.image }}
        </div>


       <div class="form-row">
            {{ '수량 : ' }} {{ form.cnt }}
        </div>

        <div class="form-row">
            {{'가격 : ' }} {{ form.price }}
        </div>


        <div class="form-row">
            {{ '원산지 : ' }} {{ form.origin }}
        </div>

        <div class="form-row">
            {{ '구독평점 :   ' }}  {{form.Subscription_ratings}}
        </div>

        <div class="form-row">
            {{ '구독 후 구매수 : ' }}  {{form.purchase_after_sub}}
        </div>




        <div class="form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>

    </fieldset>

    <div class="submit-row">
        <input type="submit" value="Submit"/>
    </div>

    <script type="text/javascript">document.getElementById('id_album').focus();</script>

    </form>
        </div>

</div>
{% endblock %}